// src/components/modal/AboutModal.tsx
import Row from "@/components/grid/Row";
import Column from "@/components/grid/Column";
import {AiFillGithub} from "react-icons/ai";
import {BsCurrencyDollar, BsDiscord} from "react-icons/bs";
import {BiBook} from "react-icons/bi";
import styles from "@/styles/components/modal/AboutModal.module.scss";

export default function AboutModal() {
    /**
     * Opens a link in the default browser.
     *
     * @param url The url to open
     */
    function openLink(url: string) {
        window.open(url, "_blank");
    }

    return (
        <div className={styles.content}>
            <div className={styles.title}>
                <h1>HoloHUI Builder</h1>
                <h3>
                    &copy; {new Date().getFullYear()} Studio Archetype, All Rights Reserved.
                </h3>
            </div>
            <div className={styles.buttons}>
                <Row center>
                    <Column xs={24} lg={12}>
                        <div
                            className={styles.button}
                            onClick={() => openLink("https://github.com/Studio-Archetype/HUI-Builder")}
                        >
                            <AiFillGithub/>
                            GitHub
                        </div>
                    </Column>
                    <Column xs={24} lg={12}>
                        <div
                            className={styles.button}
                            onClick={() => openLink("https://discord.studioarchetype.net/")}
                        >
                            <BsDiscord/>
                            Discord
                        </div>
                    </Column>
                    <Column xs={24} lg={12}>
                        <div
                            className={styles.button}
                            onClick={() => openLink("https://studioarchetype.net/hologui")}
                        >
                            <BsCurrencyDollar/>
                            Purchase
                        </div>
                    </Column>
                    <Column xs={24} lg={12}>
                        <div
                            className={styles.button}
                            onClick={() => openLink("https://docs.studioarchetype.net/en/utilities/holoui")}
                        >
                            <BiBook/>
                            Documentation
                        </div>
                    </Column>
                </Row>
            </div>
        </div>
    )
}

// src/components/AboutModal.vue
<script setup lang="ts">
import Modal from '@/components/modal/ModalBase.vue';
import ModalToolbar from '@/components/modal/ModalToolbar.vue';
import ModalFooter from '@/components/modal/ModalFooter.vue';
import ModalBody from '@/components/modal/ModalBody.vue';
import { faDiscord, faGithub } from '@fortawesome/free-brands-svg-icons';

export interface AboutModalProps {
  open?: boolean;
}

const emit = defineEmits(['close']);
const props = withDefaults(defineProps<AboutModalProps>(), {
  open: false,
});

function close() {
  emit('close');
}

const buildNumber = 1;
</script>

<template>
  <modal :open="props.open" @backgroundClick="close" width="35%" height="75%">
    <modal-toolbar>
      <template #title>About Application</template>
      <template #actions>
        <button class="button icon faint" @click="close">
          <font-awesome-icon fixed-width icon="close"></font-awesome-icon>
        </button>
      </template>
    </modal-toolbar>
    <modal-body>
      <div class="page topology">
        <h2>HUI Builder</h2>
        <p>
          &copy; {{ new Date().getFullYear() }} Studio Archetype, All Rights
          Reserved.
        </p>

        <div class="buttons">
          <a
            class="button"
            href="https://github.com/Studio-Archetype/HUI-Builder"
          >
            <font-awesome-icon fixed-width :icon="faGithub"></font-awesome-icon>
            Github
          </a>

          <a
            class="button"
            href="https://github.com/Studio-Archetype/HUI-Builder"
          >
            <font-awesome-icon
              fixed-width
              :icon="faDiscord"
            ></font-awesome-icon>
            Support
          </a>

          <a class="button" href="https://studioarchetype.net/hologui">
            <font-awesome-icon
              fixed-width
              icon="dollar-sign"
            ></font-awesome-icon>
            Buy
          </a>
          <a
            class="button"
            href="https://docs.studioarchetype.net/en/utilities/hui"
          >
            <font-awesome-icon fixed-width icon="book"></font-awesome-icon>
            Docs
          </a>
        </div>
      </div>

      <modal-footer>
        <span class="text-neutral-500"> Build {{ buildNumber }} </span>
      </modal-footer>
    </modal-body>
  </modal>
</template>

<style scoped lang="scss">
.page {
  @apply flex flex-grow p-16 flex-col items-center;

  h2 {
    @apply font-light text-6xl;
  }

  p {
    @apply text-lg mt-8;
  }

  .buttons {
    @apply grid grid-cols-2 w-full mt-8 gap-2;

    .button {
      @apply text-center;
    }
  }
}
</style>
